//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 09:36:48 上午 CST 
//


package com.kjlink.quartz.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Define a DateIntervalTrigger
 * 
 * <p>Java class for calendarIntervalTriggerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calendarIntervalTriggerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.quartz-scheduler.org/xml/JobSchedulingData}abstractTriggerType">
 *       &lt;sequence>
 *         &lt;element name="misfire-instruction" type="{http://www.quartz-scheduler.org/xml/JobSchedulingData}date-interval-trigger-misfire-instructionType" minOccurs="0"/>
 *         &lt;element name="repeat-interval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="repeat-interval-unit" type="{http://www.quartz-scheduler.org/xml/JobSchedulingData}interval-unitType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calendarIntervalTriggerType", propOrder = {
    "misfireInstruction",
    "repeatInterval",
    "repeatIntervalUnit"
})
public class CalendarIntervalTriggerType
    extends AbstractTriggerType
{

    @XmlElement(name = "misfire-instruction")
    protected String misfireInstruction;
    @XmlElement(name = "repeat-interval", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger repeatInterval;
    @XmlElement(name = "repeat-interval-unit", required = true)
    protected String repeatIntervalUnit;

    /**
     * Gets the value of the misfireInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisfireInstruction() {
        return misfireInstruction;
    }

    /**
     * Sets the value of the misfireInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisfireInstruction(String value) {
        this.misfireInstruction = value;
    }

    /**
     * Gets the value of the repeatInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepeatInterval() {
        return repeatInterval;
    }

    /**
     * Sets the value of the repeatInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepeatInterval(BigInteger value) {
        this.repeatInterval = value;
    }

    /**
     * Gets the value of the repeatIntervalUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeatIntervalUnit() {
        return repeatIntervalUnit;
    }

    /**
     * Sets the value of the repeatIntervalUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeatIntervalUnit(String value) {
        this.repeatIntervalUnit = value;
    }

}
