//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 09:36:48 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.quartz-scheduler.org/xml/JobSchedulingData", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kjlink.quartz.schema;
