//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 09:36:48 上午 CST 
//


package com.kjlink.quartz.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Define a Trigger
 * 
 * <p>Java class for triggerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="triggerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="simple" type="{http://www.quartz-scheduler.org/xml/JobSchedulingData}simpleTriggerType"/>
 *         &lt;element name="cron" type="{http://www.quartz-scheduler.org/xml/JobSchedulingData}cronTriggerType"/>
 *         &lt;element name="calendar-interval" type="{http://www.quartz-scheduler.org/xml/JobSchedulingData}calendarIntervalTriggerType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "triggerType", propOrder = {
    "simple",
    "cron",
    "calendarInterval"
})
public class TriggerType {

    protected SimpleTriggerType simple;
    protected CronTriggerType cron;
    @XmlElement(name = "calendar-interval")
    protected CalendarIntervalTriggerType calendarInterval;

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTriggerType }
     *     
     */
    public SimpleTriggerType getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTriggerType }
     *     
     */
    public void setSimple(SimpleTriggerType value) {
        this.simple = value;
    }

    /**
     * Gets the value of the cron property.
     * 
     * @return
     *     possible object is
     *     {@link CronTriggerType }
     *     
     */
    public CronTriggerType getCron() {
        return cron;
    }

    /**
     * Sets the value of the cron property.
     * 
     * @param value
     *     allowed object is
     *     {@link CronTriggerType }
     *     
     */
    public void setCron(CronTriggerType value) {
        this.cron = value;
    }

    /**
     * Gets the value of the calendarInterval property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarIntervalTriggerType }
     *     
     */
    public CalendarIntervalTriggerType getCalendarInterval() {
        return calendarInterval;
    }

    /**
     * Sets the value of the calendarInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarIntervalTriggerType }
     *     
     */
    public void setCalendarInterval(CalendarIntervalTriggerType value) {
        this.calendarInterval = value;
    }

}
